apiVersion: apps/v1
kind: Deployment
metadata:
  name: noretto-web
  namespace: noretto
  labels:
    app: noretto-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: noretto-web
  template:
    metadata:
      labels:
        app: noretto-web
    spec:
      containers:
        - name: noretto-web
          image: shashank1248/noretto-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_PAYLOAD_URL
              value: "http://46.62.135.233:30081"
            - name: REVALIDATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: noretto-web-secrets
                  key: revalidation-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
