apiVersion: v1
kind: Secret
metadata:
  name: noretto-web-secrets
  namespace: noretto
type: Opaque
stringData:
  # Generate a secure secret: openssl rand -base64 32
  revalidation-secret: "CpFThsRqfAdcALeFuSCdP76K+RtCaahv5WGjjCWxwTI="
