apiVersion: v1
kind: Service
metadata:
  name: noretto-web
  namespace: noretto
spec:
  type: NodePort
  selector:
    app: noretto-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
